# Programming intro
- functions
- controll flow
- loops
- classes

## Functions
- similar in principle to R:
  - take inputs, calculate stuff, (maybe) return stuff
- the syntax is a bit different:
  - we don't assign functions, we define them: `def my_function(inputs):`
  - codeblock follows indented below

In [18]:
def my_function(num, expo):
  num **= expo # what is this? -> num = num ** expo
  return num

In [19]:
print(my_function(5, 2))

25

In [27]:
# type hinting:
# very advanced, not necessary but good practice for readable and reusable code
# define types of in- and outputs
# set defaults
# add docstring:
def my_function(num: int | float, expo: int | float = 2) -> int | float:
  '''
  Takes a base and exponent and returns the exponentiated base
          Parameters:
                  num (int|float): The base, can be an integer or float
                  expo (int|float): The exponent, can be an integer or float (default is 2)
          Returns:
                  exponentiated (int|float): Exponentiated base
  '''
  num **= expo 
  return num

In [28]:
print(my_function(5))

25

# Control Flow
- as opposed to R, we don't need brackets here, just the keyword, the condition and a colon
- the keywords in python are:
  - `if condition:`
  - `elif condition:`
  - `else:`
- code blocks are indented below the keywords

In [34]:
a = -10
if a > 3:
  print('a is greater than 3!')
elif (a <= 3) & (a > 0):
  print('a is lesser than 3, but greater than 0')
else:
  print('a is lesser than or equals 0')

a is lesser than or equals 0

## Loops:
- the rationale is, again, very similar to R 
  - for things in container, do stuff
  - while condition is tru, do stuff
- the syntax is a bit different though:
  - initiallize: 
    - for: `for iterator in container:` -> you can name the iterator whatever you want, convention is `i` for the first one, `j`for the second, etc.
    - while: `while condition:`
  - codeblock: indent by one tab and code away!

In [2]:
# simple for loop:
for i in [1,2,3]:

  t2 = i * 2

  print(f'{i} times 2 = {t2}')

1 times 2 = 2
2 times 2 = 4
3 times 2 = 6

In [7]:
# simple while loop:
counter = 1

while counter < 10:
  c_square = counter ** 2
  print(f'{counter}^2 = {c_square}')
  counter += 1 # what does this do? -> counter = counter + 1

1^2 = 1
2^2 = 4
3^2 = 9
4^2 = 16
5^2 = 25
6^2 = 36
7^2 = 49
8^2 = 64
9^2 = 81

# A (very) brief introduction into classes
- classes are similar to packages and can hold multiple functions
- great for reusable code and packaging!
- rely on object oriented programming (OOP) and are therefore perfect for agent based modeling (ABM)
- three main structures:
  - definition by calling `class():`
  - initiallizations by calling `def __init__(self, more_inputs):`
    - in the indented block below we can also define constants
    - we always have to include "self" as an input, as everythin has to reference the class (-> itself)
  - "free" space for all our functions! 
    - they are defined mostly in the same way, but have to include the input "self"

In [67]:
class toolbox:
  '''
  An example class that holds a few functions
  '''
  def __init__(self): # no inputs yet
    pass

  def square(self, base: int | float) -> int | float:
    return base ** 2

  def multistring(self, text: str, multi: int) -> str:
    return text * multi

  def hello(self) -> str:
    print('hello world!')

In [68]:
tb = toolbox()

In [69]:
tb.hello()

hello world!

In [71]:
tb.multistring('hello', 3)

'hellohellohello'

In [105]:
# a bit more advanced to demonstrate the potential
import pandas as pd
class Agent:
  '''
  A very basic ABM Agent class
  '''
  def __init__(
      self,
      name: str,
      city: str,
      preference: str,
      ):
    self.name = name
    self.city = city
    self.preference = preference

    self.meetings = []

  def meeting(self, alter, dialog=True):

    if self.city == alter.city:
      if self.preference == alter.preference:
        if (self.city == 'Münster') & (self.preference == 'coffee'):
          if dialog:
            print(f'let us meet over {self.preference} and go to the roestbar!')
          meet_bev = 'roestbar_coffee'
        else:
          if dialog:
            print(f'let us meet over {self.preference}!')
          meet_bev = self.preference
      else:
        if dialog:
            print(f'I want to get a {self.preference}, I believe they also have {alter.preference}!')
        meet_bev = self.preference

      meet_place = self.city
    else:
      if dialog:
            print(f'let us meet via zoom, I just have to get a {self.preference} first!')
      meet_place = f'{self.city} - zoom'
      meet_bev = self.preference

    self.meetings.append(dict(
        meet_alter=alter.name,
        meet_place=meet_place,
        meet_bev=meet_bev
    ))

  def show_meetings(self):
    meetings_df = pd.DataFrame(self.meetings)
    return meetings_df

In [106]:
a = Agent('Johanna', 'Münster', 'coffee')
b = Agent('Said', 'Hannover', 'coffee')
c = Agent('Anna', 'Münster', 'tea')
d = Agent('Lena', 'Münster', 'coffee')

In [107]:
a.preference

'coffee'

In [108]:
c.meeting(d)

I want to get a tea, I believe they also have coffee!

In [110]:
for m in [b, c, d]:
  a.meeting(m, dialog=False)

all_meetings = a.show_meetings()
all_meetings

  meet_alter      meet_place         meet_bev
0       Said  Münster - zoom           coffee
1       Anna         Münster           coffee
2       Lena         Münster  roestbar_coffee

In [111]:
b.city = 'Münster'
a.meeting(b, dialog=False)
all_meetings = a.show_meetings()
all_meetings

  meet_alter      meet_place         meet_bev
0       Said  Münster - zoom           coffee
1       Anna         Münster           coffee
2       Lena         Münster  roestbar_coffee
3       Said         Münster  roestbar_coffee